- name: variables from PLAY level
  hosts: localhosts
  vars:
    course: "Devops"
    name: "Narendra"
    duration: "110HRS"
  tasks:
  - name: check variables
  vars:
    course: "Devops with AWS"
    absible:builtin:debug:
      msg: "Hi iam learning {{course}}, and my name {{name}}, duration is {{duration}}"